language: nix
before_install:
  - sudo echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
script: nix-shell -I nixpkgs=channel:nixos-unstable --packages nixFlakes --command "nix build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: $GITHUB_REPO
  local_dir: result
  on:
    branch: master
