before_install:
  - sudo sh <(curl -L https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200804_ed52cf6/install)
script: sudo nix build --experimental-features 'nix-command flakes'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: $GITHUB_REPO
  local_dir: result
  on:
    branch: master
