language: nix
before_install:
  - sudo nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
  - sudo nix-channel --add https://nixos.org/channels/nixos-18.09 nixos-18
  - sudo nix-channel --update
script: nix-build


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: $GITHUB_REPO
  local_dir: result
  on:
    branch: master
