language: nix
script: nix-shell -I nixpkgs=channel:nixos-unstable --packages nixFlakes --command "nix --experimental-features 'nix-command flakes' build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: $GITHUB_REPO
  local_dir: result
  on:
    branch: master
